{{ if .Values.isProduction }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: saas-filestore
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/saas1/filestore"
{{ end }}