{{ if .Values.isProduction }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: www-pvc-snapshot
  namespace: {{ .Values.namespace }}
spec:
  volumeSnapshotClassName: csi-hostpath-snapclass
  source:
    persistentVolumeClaimName: www-pvc
{{ end }}