apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: saas
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: saas
    sources:
      direct: true
  # - origin:
  #     kind: Warehouse
  #     name: features
  #   sources:
  #     direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/dev
        - name: argocdApp
          value: saas-dev

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: saas
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: saas
    sources:
      stages:
        - dev
  # - origin:
  #     kind: Warehouse
  #     name: features
  #   sources:
  #     stages:
  #       - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/staging
        - name: argocdApp
          value: saas-staging

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: saas
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: saas
    sources:
      stages:
        - staging
  # - origin:
  #     kind: Warehouse
  #     name: features
  #   sources:
  #     stages:
  #       - staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/prod
        - name: argocdApp
          value: saas-prod