apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: saas
  namespace: saas
spec:
  subscriptions:
  - image:
      repoURL: docker.io/nikolinmajmari/odoo_estate
      imageSelectionStrategy: NewestBuild

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: features
  namespace: saas
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: 'https://github.com/nikolinmajmari/odoo-saas.git'
#       includePaths:
#       - base/feature-flags.yaml