apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.3.3
    helm:
      parameters:
        - name: api.adminAccount.passwordHash
          value: $$2a$$10$$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm
          # Note: A bcrypt-hashed password will contain `$` characters that
          # MUST each be escaped as `$$`
          # p6LjXDAOtfv4sQ48yjDuVlGlpMp1y1ka
        - name: api.adminAccount.tokenSigningKey
          value: iwishtowashmyirishwristwatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true