apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: saas
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: saas-*
    server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - 'https://github.com/nikolinmajmari/odoo-saas.git'