{{- if .Values.isProduction }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: saas-backup-job
  namespace: {{ .Values.namespace }}
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  echo "Triggering CloudNativePostgreSQL backup..."
                  kubectl apply -f - <<EOF
                  apiVersion: postgresql.cnpg.io/v1
                  kind: Backup
                  metadata:
                    name: postgres-backup
                    namespace: {{ .Values.namespace }}
                  spec:
                    cluster:
                      name: postgresql-cluster
                  EOF

                  echo "Waiting for PostgreSQL backup to finish..."

                  echo "Starting volume snapshot creation"
                  
                  kubectl apply -f - <<EOF
                  apiVersion: snapshot.storage.k8s.io/v1
                  kind: VolumeSnapshot
                  metadata:
                    name: www-pvc-snapshot
                    namespace: saas-prod
                  spec:
                    volumeSnapshotClassName: csi-hostpath-snapclass  # Adjust to your CSI snapshot class
                    source:
                      persistentVolumeClaimName: www-pvc
                  EOF

                  echo "Backup and Snapshot completed!"
          restartPolicy: OnFailure
          serviceAccountName: backup-job-sa

{{- end }}