{{- if .Values.isProduction }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-job-sa
  namespace: saas-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-job-role
  namespace: saas-prod
rules:
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["backups","volumesnapshots"]
    verbs: ["get", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-job-binding
  namespace: saas-prod
subjects:
  - kind: ServiceAccount
    name: backup-job-sa
    namespace: saas-prod
roleRef:
  kind: Role
  name: backup-job-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}