apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-cluster-backup
spec:
  schedule: "*/5 * * * *"
  backupOwnerReference: self
  cluster:
    name: postgresql-cluster
  storage:
    pvc: postgresql-backup-pvc