apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace:  {{ .Values.namespace }}
spec:
  schedule: "*/10 * * * *"  # Every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgresql-backup
            image: postgres:13  # Choose an appropriate version
            env:
              - name: PGHOST
                value: "postgresql"  # Set this to your PostgreSQL service name
              - name: PGPORT
                value: "5432"
              - name: PGUSER
                value: "postgres"  # Set your user if different
              - name: PGPASSWORD
                value: ODOO
              - name: PGDATABASE
                value: "your_db"  # Database name to back up
            volumeMounts:
              - name: backup-storage
                mountPath: /backups  # Directory to store backups
            command:
              - "/bin/bash"
              - "-c"
              - |
                PGPASSWORD=$PGPASSWORD pg_dump -h $PGHOST -U $PGUSER $PGDATABASE > /backups/backup_$(date +%F_%H-%M-%S).sql
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgresql-backup-pvc
