apiVersion: v1
kind: Secret
metadata:
  name: postgresql-cluster-odoo
type: kubernetes.io/basic-auth
stringData:
  username: odoo
  password: odoo
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace:  {{ .Values.namespace }}
spec:
  instances: 1
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      secret:
        owner: odoo
        name: postgresql-cluster-odoo
        postInitSQL:
        - ALTER ROLE odoo WITH SUPERUSER
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi
    # volumeClaimTemplate:
    #   metadata:
    #     name: postgresql-cluster-pvc
    #   spec:
    #     accessModes:
    #       - ReadWriteOnce:
    #     resources:
    #       requests:
    #         storage: 1Gi
    #     storageClassName: standard
  backup:
    barmanObjectStore:
      destinationPath: s3://saas-prod-bucket/
      endpointURL: http://minio-service:9000
      s3Credentials:
        accessKeyId:
          name: minio-creds  # Secret name
          key: access-key     # Key inside the secret
        secretAccessKey:
          name: minio-creds  # Secret name
          key: secret-key    # Key inside the secret
  # volumeMounts:
  #   - name: postgresql-backup-pvc
  #     mountPath: "/var/lib/postgresql/backup"
  # volumes:
  #   - name: postgresql-backup-pvc
  #     persistentVolumeClaim:
  #       claimName: postgresql-backup-pvc
    