apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace:  {{ .Values.namespace }}
spec:
  instances: 1
  enableSuperuserAccess: true
  bootstrap:
{{- if .Values.isProduction }}
    # initdb:
    #   secret:
    #     name: postgresql-cluster-odoo
    #   postInitSQL:
    #   - CREATE USER odoo WITH PASSWORD 'odoo'
    #   - GRANT ALL ON SCHEMA public TO odoo
    #   - ALTER ROLE odoo with CREATEDB
    #   - ALTER ROLE odoo with CREATEROLE
    recovery:
      source: postgresql-cluster
{{- else }}
    recovery:
      source: postgresql-cluster
{{- end}}
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi
    {{- if .Values.isProduction }}
    volumeClaimTemplate:
      metadata:
        name: postgresql-cluster-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    {{- end }}
{{- if .Values.isProduction }}
  backup:
    barmanObjectStore:
      destinationPath: s3://saas-prod-bucket/
      endpointURL: http://minio-service:9000
      s3Credentials:
        accessKeyId:
          name: minio-creds  # Secret name
          key: accesskey     # Key inside the secret
        secretAccessKey:
          name: minio-creds  # Secret name
          key: secretkey    # Key inside the secret
{{- end }}
{{- if not .Values.isProduction }}
  externalClusters:
    - name: postgresql-cluster
      barmanObjectStore:
        destinationPath: s3://saas-prod-bucket/
        endpointURL: http://minio-service.saas-prod.svc.cluster.local:9000
        s3Credentials:
          accessKeyId:
            name: minio-creds
            key: accesskey
          secretAccessKey:
            name: minio-creds
            key: secretkey
        wal:
          maxParallel: 8
{{- end }}
  
  # volumeMounts:
  #   - name: postgresql-backup-pvc
  #     mountPath: "/var/lib/postgresql/backup"
  # volumes:
  #   - name: postgresql-backup-pvc
  #     persistentVolumeClaim:
  #       claimName: postgresql-backup-pvc
    