apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace:  {{ .Values.namespace }}
spec:
  instances: 1

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi
    volumeClaimTemplate:
      metadata:
        name: postgresql-cluster-pvc
      spec:
        accessModes:
          - ReadWriteOnce:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
  backup:
    target: "primary"
    