apiVersion: v1
kind: Secret
metadata:
  name: postgresql-cluster-odoo
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: odoo
  password: odoo

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  accesskey: azV0WGFvcTdzcnVJZTdTMXZUa00=
  secretkey: Z3R6WndZVXNmYmhRSml1elZZRWJkbUM0TjhqTURheXRlQnpNUHlMaA==