apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-www-pvc-clone
  namespace: saas-prod
spec:
  from:
    - group: ""
      kind: PersistentVolumeClaim
      namespace:  saas-staging
  to:
    - group: snapshot.storage.k8s.io
      kind: VolumeSnapshot
      name: www-pvc-snapshot