apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }} 
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069