apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ if .Values.isStagging }}
  dataSource:
    name: www-pvc-snapshot
    namespaces: saas-prod
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
{{ end }}